using Microsoft.Xna.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Game.Utilities.Constants
{
    public static class MarioSpriteConstants
    {
        public const int RESETTOZERO = 0;
        public const int STARDRAWBROWNCOUNTER = 6;
        public const int STARDRAWYELLOWGREENCOUNTER = 10;
        public const int STARDRAWORANGECOUNTER = 15;
        public const int FLAGUPDATEDELAYCOUNTER = 2;
        public const int RUNNINGUPDATEDELAY = 3;
        public static readonly Vector2 DEADMARIOSOURCECOORDINATES = new Vector2(390, 16);
        public static readonly Vector2 DEADMARIOWIDTHHIEGHT = new Vector2(14, 13);
        public static readonly Vector2 FIREFLAGMARIOWIDTHHEIGHT = new Vector2(14, 30);
        public static readonly Vector2 FIRSTFIREFLAGSOURCECOORDINATES = new Vector2(363, 158);
        public static readonly Vector2 SECONDFIREFLAGSOURCECOORDINATES = new Vector2(390, 159);
        public static readonly Vector2 FIRELEFTCROUCHINGWIDTHHEIGHT = new Vector2(16, 21);
        public static readonly Vector2 FIRELEFTCROUCHINGSOURCE = new Vector2(0, 127);
        public static readonly Vector2 FIRELEFTIDLEWIDTHHEIGHT = new Vector2(16, 31);
        public static readonly Vector2 FIRELEFTIDLESOURCE = new Vector2(180, 122);
        public static readonly Vector2 FIRELEFTJUMPWIDTHHEIGHT = new Vector2(16, 31);
        public static readonly Vector2 FIRELEFTJUMPSOURCE = new Vector2(27, 122);
        public static readonly Vector2 FIRSTFIRELEFTRUNNINGSOURCE = new Vector2(152, 122);
        public static readonly Vector2 SECONDFIRELEFTRUNNINGSOURCE = new Vector2(128, 122);
        public static readonly Vector2 THIRDFIRELEFTRUNNINGSOURCE = new Vector2(102, 123);
        public static readonly Vector2 FIRSTFIRELEFTRUNNINGDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 SECONDFIRELEFTRUNNINGDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 THIRDFIRELEFTRUNNINGDIMENSIONS = new Vector2(16, 29);
        public static readonly Vector2 FIRELEFTWISTWIDTHHEIGHT = new Vector2(16, 31);
        public static readonly Vector2 FIRELEFTWISTSOURCE = new Vector2(337, 122);
        public static readonly Vector2 FIRERIGHTCROUCHSOURCE = new Vector2(389,127);
        public static readonly Vector2 FIRERIGHTCROUCHSDIMENSIONS = new Vector2(16,21);
        public static readonly Vector2 FIRERIGHTIDLESOURCE = new Vector2(209,122);
        public static readonly Vector2 FIRERIGHTIDLEDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRERIGHTJUMPINGSOURCE = new Vector2(362,122);
        public static readonly Vector2 FIRERIGHTJUMPINGDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRSTFIRERIGHTRUNNINGSOURCE = new Vector2(237, 122);
        public static readonly Vector2 SECONDFIRERIGHTRUNNINGSOURCE = new Vector2(264, 122);
        public static readonly Vector2 THIRDFIRERIGHTRUNNINGSOURCE = new Vector2(287,123);
        public static readonly Vector2 FIRSTFIRERIGHTRUNNINGDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 SECONDFIRERIGHTRUNNINGDIMENSIONS = new Vector2(16, 30);
        public static readonly Vector2 THIRDFIRERIGHTRUNNINGDIMENSIONS = new Vector2(16, 29);
        public static readonly Vector2 FIRERIGHTTWISTSOURCE = new Vector2(52, 122);
        public static readonly Vector2 FIRERIGHTTWISTDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRETHROWLEFTSOURCE = new Vector2(77, 122);
        public static readonly Vector2 FIRETHROWLEFTDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRETHROWRIGHTSOURCE = new Vector2(312, 122);
        public static readonly Vector2 FIRETHROWRIGHTDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 NORMALFLAGMARIOWIDTHHEIGHT = new Vector2(14, 30);
        public static readonly Vector2 FIRSTNORMALFLAGSOURCE = new Vector2(363, 89);
        public static readonly Vector2 SECONDNORMALFLAGSOURCE = new Vector2(390, 88);
        public static readonly Vector2 NORMALLEFTCROUCHSOURCE = new Vector2(0,57);
        public static readonly Vector2 NORMALLEFTCROUCHDIMENSIONS = new Vector2(16, 21);
        public static readonly Vector2 NORMALLEFTIDLESOURCE = new Vector2(180,52);
        public static readonly Vector2 NORMALLEFTIDLEDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 NORMALLEFTJUMPSOURCE = new Vector2(30, 52);
        public static readonly Vector2 NORMALLEFTJUMPDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRSTNORMALLEFTRUNNINGSOURCE = new Vector2(150,52);
        public static readonly Vector2 SECONDNORMALLEFTRUNNINGSOURCE = new Vector2(121,52);
        public static readonly Vector2 THIRDNORMALLEFTRUNNINGSOURCE = new Vector2(90,53);
        public static readonly Vector2 FIRSTNORMALLEFTRUNNINGDIMENSIONS = new Vector2(16,31);
        public static readonly Vector2 SECONDNORMALLEFTRUNNINGDIMENSIONS = new Vector2(16,30);
        public static readonly Vector2 THIRDNORMALLEFTRUNNINGDIMENSIONS = new Vector2(16,29);
        public static readonly Vector2 NORMALLEFTTWISTSOURCE = new Vector2(329,52);
        public static readonly Vector2 NORMALLEFTTWISTDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 NORMALRIGHTCROUCHSOURCE = new Vector2(389,57);
        public static readonly Vector2 NORMALRIGHTCROUCHDIMENSIONS = new Vector2(16, 21);
        public static readonly Vector2 NORMALRIGHTIDLESOURCE = new Vector2(209,52);
        public static readonly Vector2 NORMALRIGHTIDLEDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 NORMALRIGHTJUMPSOURCE = new Vector2(359,52);
        public static readonly Vector2 NORMALRIGHTJUMPDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 FIRSTNORMALRIGHTRUNNINGSOURCE = new Vector2(239,52);
        public static readonly Vector2 SECONDNORMALRIGHTRUNNINGSOURCE = new Vector2(270,52);
        public static readonly Vector2 THIRDNORMALRIGHTRUNNINGSOURCE = new Vector2(299,53);
        public static readonly Vector2 FIRSTNORMALRIGHTRUNNINGDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 SECONDNORMALRIGHTRUNNINGDIMENSIONS = new Vector2(16, 30);
        public static readonly Vector2 THIRDNORMALRIGHTRUNNINGDIMENSIONS = new Vector2(16, 29);
        public static readonly Vector2 NORMALRIGHTTWISTSOURCE = new Vector2(60, 52);
        public static readonly Vector2 NORMALRIGHTTWISTDIMENSIONS = new Vector2(16, 31);
        public static readonly Vector2 SMALLFLAGMARIODIMENSIONS = new Vector2(14, 16);
        public static readonly Vector2 FIRSTSMALLFLAGSOURCE = new Vector2(331,30);
        public static readonly Vector2 SECONDSMALLFLAGSOURCE = new Vector2(361,30);
        public static readonly Vector2 SMALLLEFTIDLESOURCE = new Vector2(181,0);
        public static readonly Vector2 SMALLLEFTIDLEDIMENSIONS = new Vector2(16,15);
        public static readonly Vector2 SMALLLEFTJUMPSOURCE = new Vector2(29, 0);
        public static readonly Vector2 SMALLLEFTJUMPDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 FIRSTSMALLLEFTRUNNINGSOURCE = new Vector2(150,0);
        public static readonly Vector2 SECONDSMALLLEFTRUNNINGSOURCE = new Vector2(121,0);
        public static readonly Vector2 THIRDSMALLLEFTRUNNINGSOURCE = new Vector2(89,0);
        public static readonly Vector2 FIRSTSMALLLEFTRUNNINGDIMENSIONS = new Vector2(16, 14);
        public static readonly Vector2 SECONDSMALLLEFTRUNNINGDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 THIRDSMALLLEFTRUNNINGDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 SMALLLEFTTWISTSOURCE = new Vector2(60, 0);
        public static readonly Vector2 SMALLLEFTTWISTDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 SMALLRIGHTIDLESOURCE = new Vector2(211, 0);
        public static readonly Vector2 SMALLRIGHTIDLEDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 SMALLRIGHTJUMPSOURCE = new Vector2(359, 0);
        public static readonly Vector2 SMALLRIGHTJUMPDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 SMALLRIGHTTWISTSOURCE = new Vector2(331, 0);
        public static readonly Vector2 SMALLRIGHTTWISTDIMENSIONS = new Vector2(16, 15);

        public static readonly Vector2 FIRSTSMALLRIGHTRUNNINGSOURCE = new Vector2(241,0);
        public static readonly Vector2 SECONDSMALLRIGHTRUNNINGSOURCE = new Vector2(272,0);
        public static readonly Vector2 THIRDSMALLRIGHTRUNNINGSOURCE = new Vector2(300,0);
        public static readonly Vector2 FIRSTSMALLRIGHTRUNNINGDIMENSIONS = new Vector2(16, 14);
        public static readonly Vector2 SECONDSMALLRIGHTRUNNINGDIMENSIONS = new Vector2(16, 15);
        public static readonly Vector2 THIRDSMALLRIGHTRUNNINGDIMENSIONS = new Vector2(16, 15);
    }
}
